//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfClientNamedPipe.WCFNamedPipe {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFNamedPipe.IWCFNamedPipe")]
    public interface IWCFNamedPipe {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFNamedPipe/calculateDays", ReplyAction="http://tempuri.org/IWCFNamedPipe/calculateDaysResponse")]
        int calculateDays(int day, int Month, int year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFNamedPipe/calculateDays", ReplyAction="http://tempuri.org/IWCFNamedPipe/calculateDaysResponse")]
        System.Threading.Tasks.Task<int> calculateDaysAsync(int day, int Month, int year);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWCFNamedPipeChannel : WpfClientNamedPipe.WCFNamedPipe.IWCFNamedPipe, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WCFNamedPipeClient : System.ServiceModel.ClientBase<WpfClientNamedPipe.WCFNamedPipe.IWCFNamedPipe>, WpfClientNamedPipe.WCFNamedPipe.IWCFNamedPipe {
        
        public WCFNamedPipeClient() {
        }
        
        public WCFNamedPipeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WCFNamedPipeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFNamedPipeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFNamedPipeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int calculateDays(int day, int Month, int year) {
            return base.Channel.calculateDays(day, Month, year);
        }
        
        public System.Threading.Tasks.Task<int> calculateDaysAsync(int day, int Month, int year) {
            return base.Channel.calculateDaysAsync(day, Month, year);
        }
    }
}
